### ISSUE TITLE
`enif_cond_wait` loop

### ISSUE THREAD

**Issue by jonatanklosko** [cocoa-xu/nif_call#1]
Awesome job!

Just a quick note to remember, from [the docs](https://www.erlang.org/doc/apps/erts/erl_driver.html#erl_drv_cond_wait):

> erl_drv_cond_wait can return even if no one has signaled or broadcast on the condition variable. Code calling erl_drv_cond_wait is always to be prepared for erl_drv_cond_wait returning even if the condition that the thread was waiting for has not occurred. That is, when returning from erl_drv_cond_wait, always check if the condition has occurred, and if not call erl_drv_cond_wait again.

So it should be something like:

```
while (callback_res_result_not_set) {
  enif_cond_wait(callback_res->cond, callback_res->mtx);
}
```

**Comment by cocoa-xu** [comment]
Thanks @jonatanklosko! I didn't notice this one, I'll push a commit to fix it!
