### ISSUE TITLE
Make nif_call safe

### ISSUE THREAD

**Issue by josevalim** [cocoa-xu/nif_call#8]
This is an idea I discussed with @cocoa-xu (please close if it was already implemented!) to make `nif_call` safe. Today, if the called code crashes, the NIF will be stuck forever. We can also use this opportunity to simplify the API and require less code generation, instead by asking users to add processes to their own supervision tree:

```elixir
defmodule NifCall.Runner do
  use GenServer
  
  def start_link(opts) do
    GenServer.start_link(__MODULE__, :ok, opts)
  end
  
  def register(name, function) when is_function(function, 1) do
    GenServer.call(name, {:register, self(), function}, :infinity)
  end
  
  def unregister(name, {_pid, ref}) do
    GenServer.call(name, {:unregister, ref}, :infinity)
  end
  
  def init(:ok) do
    {:ok, %{}}
  end
  
  def handle_call({:register, owner, function}, _from, state) do
    ref = Process.monitor(owner)
    {:reply, {self(), ref}, Map.put(state, ref, function)}
  end
  
  def handle_call({:unregister, ref}, _from, state) do
    Process.demonitor(ref, [:flush])
    {:reply, :ok, Map.delete(state, ref)}
  end
  
  def handle_info({:DOWN, ref, _, _, _}, state) do
    {:noreply, Map.delete(state, ref)}
  end
    
  def handle_info({:execute, resource, ref, arg}, state) do
    function = Map.fetch!(state, ref)
    
    pid = spawn(fn ->
      try do
        NifCall.NIF.back_to_c(resource, {:ok, function.(arg)})
      catch
        kind, reason -> NifCall.NIF.back_to_c(resource, {kind, reason})
      end
    end)

    _ = Process.monitor(pid, tag: {:eval, resource})
    {:noreply, state}
  end

  def handle_info({{:eval, resource}, _, _, _, reason}, state) do
    if reason != :normal do
      NifCall.NIF.back_to_c(resource, {:exit, reason})
    end
    
    {:noreply, state}
  end
end
  

@doc """
Runs a function that invokes a NIF with the ability to call back.

## Examples

First start the NifCall.Runner in your supervision tree:

    {NifCall.Runner, name: MyApp.NifRunner}

Then call this function with the NifRunner:
    
    to_be_called =
      fn arg ->
        # This will be called by the NIF with arg
      end
    
    to_run =
      fn ->
        # This is the code that you want to run
      end
    
    NifCall.run(MyApp.NifRunner, to_be_called, fn tag ->
      MyLibraryNif.invoke(tag)
    end)
"""
def run(name, to_be_called, fun) do
  tag = NifCall.Runner.register(name, to_be_called)
  
  try do
    fun.(tag)
  after
    NifCall.Runner.unregister(name, tag)
  end
end
```

Tests should be written showing there is no starvation in case of throws, exits, errors, nor broken links. Even then, I'd perhaps argue adding some warnings to the library README advocating for caution. Just in case! :)

Thank you @cocoa-xu!

**Comment by cocoa-xu** [comment]
Hi @josevalim, thanks for pasting the code here! I recently got a cold or a winter flu, and it also infected my left eye. I'll be implementing this once my eye's condition is getting better. Right now it still hurts and I can't keep them open for a long time😭

**Comment by josevalim** [comment]
Oh noes! I am so sorry to hear, hopefully you will recover soon. :)

FWIW, I didn't post to rush you, but to document it because it came up in a discussion with @polvalente!

**Comment by cocoa-xu** [comment]
> hopefully you will recover soon. :)

Thank you Jose! I also hope that I can also jump back soon ^_^

> FWIW, I didn't post to rush you, 

Yeah, I got that😊 I'm also like leaving a note here so others would know I'm working on this one (I mean very soon, got my medicine yesterday and probably can continue on this on Saturday or Sunday)
